//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinanceViewer.Net.Models.DbModels
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class financeviewerEntities : DbContext
    {
        public financeviewerEntities()
            : base("name=financeviewerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<fv_users> fv_users { get; set; }
        public virtual DbSet<fv_views> fv_views { get; set; }
        public virtual DbSet<fv_years> fv_years { get; set; }
    }
}
