//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinanceViewer.Net.Models.DbModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class fv_users
    {
        public string u_name { get; set; }
        public string u_password { get; set; }
        public int u_isLocked { get; set; }
        public string u_firstName { get; set; }
        public string u_lastName { get; set; }
    }
}
