//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinanceViewer.Net.Models.DbModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class fv_views
    {
        public int v_id { get; set; }
        public string v_y_year { get; set; }
        public string v_u_name { get; set; }
        public string v_name { get; set; }
        public string v_description { get; set; }
        public string v_html_id { get; set; }
        public string v_notes { get; set; }
        public string v_profile_url { get; set; }
        public string v_month_01 { get; set; }
        public string v_month_02 { get; set; }
        public string v_month_03 { get; set; }
        public string v_month_04 { get; set; }
        public string v_month_05 { get; set; }
        public string v_month_06 { get; set; }
        public string v_month_07 { get; set; }
        public string v_month_08 { get; set; }
        public string v_month_09 { get; set; }
        public string v_month_10 { get; set; }
        public string v_month_11 { get; set; }
        public string v_month_12 { get; set; }
    }
}
