//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinanceViewer.Net.Models.DbModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class fv_years
    {
        public string y_year { get; set; }
        public string y_u_name { get; set; }
    }
}
